[dir]
#  Commonly used base METplus variables
#  Location of METplus code
METPLUS_BASE = {ENV[METPLUS_ROOT]}

# Location of configuration files used by MET applications
CONFIG_DIR = {METPLUS_BASE}/parm/met_config

# Location of LOG_DIR
LOG_DIR = {ENV[LOGDIR]}

[config]
LOG_LEVEL = {ENV[LOG_LEVEL]}
LOG_MET_OUTPUT_TO_METPLUS = yes

