[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/model_applications/tc_and_extra_tc/TCPairs_TCStat_fcstADECK_obsBDECK_ATCF_BasicExample.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = TCPairs


###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

# Since tasks are set up to run once per cycle, the START_DATE will always equal the END_DATE
LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG = {{start_date}}
INIT_END = {{start_date}}

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

# TCPairs

INPUT_BASE = {{input_dir}}
OUTPUT_BASE = {{output_dir}}

TC_PAIRS_ADECK_INPUT_DIR = {INPUT_BASE}
TC_PAIRS_BDECK_INPUT_DIR = {{best_track}}

TC_PAIRS_ADECK_TEMPLATE = {{adeck_template}}
TC_PAIRS_BDECK_TEMPLATE = b{basin}{cyclone}{init?fmt=%Y}.dat
TC_PAIRS_READ_ALL_FILES = no

TC_PAIRS_OUTPUT_DIR = {OUTPUT_BASE}/TCPAIRS
TC_PAIRS_OUTPUT_TEMPLATE = tc_pairs.{MODEL}.{basin}{cyclone}{init?fmt=%Y}

LOG_MET_VERBOSITY = {{log_met_verbosity}}
LOG_LEVEL = {{log_level}}
LOG_METPLUS = {LOG_DIR}/metplus.TCPAIRS

###
# TCPairs Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#tcpairs
###

MODEL = {{model}}

TC_PAIRS_BASIN = {{basin}}
TC_PAIRS_CYCLONE = {{storm_id}}

TC_PAIRS_DLAND_FILE = MET_BASE/tc_data/dland_global_tenth_degree.nc

TC_PAIRS_MATCH_POINTS = TRUE
