[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/model_applications/tc_and_extra_tc/TCPairs_TCStat_fcstADECK_obsBDECK_ATCF_BasicExample.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = TCStat


###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG = {ENV[START_DATE]}
INIT_END = {ENV[END_DATE]}
INIT_INCREMENT = {ENV[INC]}
MODEL = {ENV[MODEL]}

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

# TCStat

OUTPUT_BASE = {ENV[OUTPUT_DIR]}
TC_STAT_LOOKIN_DIR = {OUTPUT_BASE}/tcpairs
TC_STAT_OUTPUT_DIR = {OUTPUT_BASE}/tcstat


LOG_MET_VERBOSITY = {ENV[LOG_MET_VERBOSITY]}
LOG_LEVEL = {ENV[LOG_LEVEL]}
LOG_METPLUS = {LOG_DIR}/metplus.{ENV[METPLUSTOOLNAME]}

###
# TCStat Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#tcstat
###

TC_STAT_LINE_TYPE = TCMPR
TC_STAT_BASIN = {ENV[BASIN]}
TC_STAT_CYCLONE = {ENV[STORM_ID]}

TC_STAT_COLUMN_STRING_NAME = LEVEL
TC_STAT_COLUMN_STRING_VAL = HU,SD,SS,TS,TD

TC_STAT_WATER_ONLY = FALSE

TC_STAT_JOB_ARGS = -job filter -dump_row {TC_STAT_OUTPUT_DIR}/tc_stat_summary.tcst -job rirw -rirw_track BOTH -rirw_exact TRUE -rirw_thresh ge30 -out_stat {TC_STAT_OUTPUT_DIR}/tc_rirw.{MODEL}.{TC_STAT_BASIN}{TC_STAT_CYCLONE}{init?fmt=%Y}.tcst
